baseURL: ""
languageCode: "en-us"
title: "William Pan"
hasCJKLanguage: true
params: 
  heading: "Starlight Pavilion"
frontmatter: 
  date: 
    - :filename
    - :default
permalinks: 
blackfriday: 
  fractions: false
  extensionsmask: 
    - noIntraEmphasis
markup: 
  goldmark: 
    extensions: 
      typographer: true
    renderer: 
      unsafe: true 